BEGIN TRANSACTION;

CREATE TABLE movies
(
  moviename         TEXT,
  lead_actor        TEXT,
  actress           TEXT,
  year_of_release    INT,
  director_name     TEXT
);

INSERT INTO movies VALUES ('3 IDIOTS','AAMIR KHAN','KAREENA KAPOOR',2009,'RAJKUMAR HIRANI');
INSERT INTO movies VALUES ('SHEERSHA','SIDDHARTH MALHOTRA','KIARA ADVANI',2021,'VISHNUVARDHAN');
INSERT INTO movies VALUES ('HAIDER','SHAHID KAPOOR','TABU',2014,'VISHAL BHARDWAJ');
INSERT INTO movies VALUES ('SWADES','SHAH RUKH KHAN','GAYATRI JOSHI',2004,'ASHUTOSH GOWARIKER');
INSERT INTO movies VALUES ('DEAR ZINDAGI','SHAH RUKH KHAN','ALIA BHATT',2016,'GUARI SHINDE');

SELECT * FROM movies;
SELECT * FROM movies where lead_actor='SHAH RUKH KHAN';
